$:
  tag_push:
    # 上传二进制包到 release 附件
    - docker:
        build: .ide/Dockerfile
      stages:
        - name: 更新日志
          image: cnbcool/changelog
          exports:
            latestChangeLog: LATEST_CHANGE_LOG
        - name: 创建 release
          type: git:release
          options:
            latest: true
            description: ${LATEST_CHANGE_LOG}
        - name: 依赖安装和部署
          script: zsh script/build.sh
        - name: release 上传附件
          image: cnbcool/attachments:latest
          settings:
            attachments:
              - dist/linux/oh-my-rime-*
              - dist/windows/oh-my-rime-*.exe
          exports:
            FILES: FILES
        - name: 输出附件
          script: echo $FILES
main:
  push:
    - name: "推送镜像"
      imports:
        - https://cnb.cool/Mintimate/secret/-/blob/main/SyncToGitHub.yml
      stages:
        - name: 自动同步代码
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/Mintimate/oh-my-rime-cli.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
            branch: main
            force: true