// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function OpenUrlBrowser(arg1) {
  return window['go']['main']['App']['OpenUrlBrowser'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function UpdateAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateAction'](arg1, arg2, arg3);
}
