// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSystemInfo():Promise<Record<string, any>>;

export function OpenUrlBrowser(arg1:string):Promise<Record<string, any>>;

export function SelectDirectory():Promise<string>;

export function UpdateAction(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;
