name: Test Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    
    - name: Install dependencies for GUI build
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev xorg-dev
    
    - name: Test build CLI
      run: |
        go mod tidy
        go build -v ./cmd/cli
    
    - name: Test build GUI (with CGO)
      run: |
        export CGO_ENABLED=1
        go build -v .
    
    - name: Run tests (skip GUI tests in CI)
      run: |
        # 只测试不依赖 GUI 的包
        go test -v ./internal/constants ./internal/downloader ./internal/system ./internal/updater ./cmd/cli
